# Path to your oh-my-fish.
set -g OMF_PATH $HOME/.local/share/omf
set -x GOPATH $HOME/code/a
set -x GOROOT /usr/local/go
set -x PATH $PATH $GOPATH $GOPATH/bin $GOROOT/bin

### Configuration required to load oh-my-fish ###
# Note: Only add configurations that are required to be set before oh-my-fish is loaded.
# For common configurations, we advise you to add them to your $OMF_CONFIG/init.fish file or
# to create a custom plugin instead.

# Load oh-my-fish configuration.
source $OMF_PATH/init.fish

# Put the line below in ~/.config/fish/config.fish:
#
status --is-interactive; and . (jump shell fish | psub)
#
# The following lines are autogenerated:

function __jump_add --on-variable PWD
  status --is-command-substitution; and return
  jump chdir
end

function j
  set -l dir (jump cd $argv)
  test -d "$dir"; and cd "$dir"
end

complete --command j --exclusive --arguments '(jump hint)'

function b
  sudo apt-get install $argv
end

function bu
  sudo apt-get update $argv
end

source /usr/local/bin/virtualenvwrapper.sh

set -x PATH $PATH $GOPATH $GOROOT/bin
